name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go version
          go mod download
          go mod tidy
      - name: Run build
        run: go build ./...
      - name: Run tests
        run: go test -v ./...
      - name: Run bench
        run: go test -bench=. -benchmem ./...
