name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go version
          go get -u github.com/stretchr/testify/require
          go get -u github.com/OlegElizarov/Shell_Sort_Golang/lib
      - name: Run build
        run: go build .
      - name: Run tests
        run: go test -v ./lib/...
      - name: Run bench
        run: go test -bench=. -benchmem ./lib/...
